version: '3'
services:

  app:
    image: glucose-prediction/app:latest
    stdin_open: true
    tty: true
    environment:
      - PROJECT_ROOT=$PWD
    volumes:
      - ./data:/root # Mount data directory
      - ./app:/app # Mount code so changes on dev server persist
    build:
      context: ./app
    command: bash -c "bash"